# Generated by Django 2.1.5 on 2019-04-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RtcMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('showmenu', 'Show to Main Menu'),),
                'managed': False,
            },
        ),
    ]
