# Generated by Django 2.1.5 on 2019-03-26 06:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowML',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ShowMorpheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ShowRTC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='support',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='files/%Y/%m', validators=[django.core.validators.FileExtensionValidator(['pdf', 'zip'], message='Zip 또는 PDF 파일만 허용 가능')]),
        ),
    ]
